// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListContainersRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Filter        map[string]*RepeatedString `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ListContainersRequest) GetFilter() map[string]*RepeatedString {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RepeatedString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedString) Reset() {
	*x = RepeatedString{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedString) ProtoMessage() {}

func (x *RepeatedString) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedString.ProtoReflect.Descriptor instead.
func (*RepeatedString) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatedString) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type FindContainerRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ContainerId   string                     `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Filter        map[string]*RepeatedString `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindContainerRequest) Reset() {
	*x = FindContainerRequest{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContainerRequest) ProtoMessage() {}

func (x *FindContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContainerRequest.ProtoReflect.Descriptor instead.
func (*FindContainerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *FindContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *FindContainerRequest) GetFilter() map[string]*RepeatedString {
	if x != nil {
		return x.Filter
	}
	return nil
}

type FindContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindContainerResponse) Reset() {
	*x = FindContainerResponse{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindContainerResponse) ProtoMessage() {}

func (x *FindContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindContainerResponse.ProtoReflect.Descriptor instead.
func (*FindContainerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *FindContainerResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type RunContainerScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerScanRequest) Reset() {
	*x = RunContainerScanRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerScanRequest) ProtoMessage() {}

func (x *RunContainerScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerScanRequest.ProtoReflect.Descriptor instead.
func (*RunContainerScanRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RunContainerScanRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type RunContainerScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ScanResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerScanResponse) Reset() {
	*x = RunContainerScanResponse{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerScanResponse) ProtoMessage() {}

func (x *RunContainerScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerScanResponse.ProtoReflect.Descriptor instead.
func (*RunContainerScanResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RunContainerScanResponse) GetResult() *ScanResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generatedAt,proto3" json:"generatedAt,omitempty"`
	Summary       *ScanSummary           `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Results       []*ScanTargetResult    `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResult) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ScanResult) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ScanResult) GetSummary() *ScanSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ScanResult) GetResults() []*ScanTargetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ScanSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Critical      int32                  `protobuf:"varint,1,opt,name=critical,proto3" json:"critical,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Medium        int32                  `protobuf:"varint,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Low           int32                  `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
	Unknown       int32                  `protobuf:"varint,5,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Total         int32                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanSummary) Reset() {
	*x = ScanSummary{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanSummary) ProtoMessage() {}

func (x *ScanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanSummary.ProtoReflect.Descriptor instead.
func (*ScanSummary) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *ScanSummary) GetCritical() int32 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *ScanSummary) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ScanSummary) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *ScanSummary) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ScanSummary) GetUnknown() int32 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

func (x *ScanSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ScanTargetResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Target          string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Class           string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Vulnerabilities []*ScanVulnerability   `protobuf:"bytes,4,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScanTargetResult) Reset() {
	*x = ScanTargetResult{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanTargetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTargetResult) ProtoMessage() {}

func (x *ScanTargetResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTargetResult.ProtoReflect.Descriptor instead.
func (*ScanTargetResult) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ScanTargetResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanTargetResult) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ScanTargetResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScanTargetResult) GetVulnerabilities() []*ScanVulnerability {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

type ScanVulnerability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PackageName      string                 `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,3,opt,name=installedVersion,proto3" json:"installedVersion,omitempty"`
	FixedVersion     string                 `protobuf:"bytes,4,opt,name=fixedVersion,proto3" json:"fixedVersion,omitempty"`
	Severity         string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Title            string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	PrimaryUrl       string                 `protobuf:"bytes,7,opt,name=primaryUrl,proto3" json:"primaryUrl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScanVulnerability) Reset() {
	*x = ScanVulnerability{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanVulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanVulnerability) ProtoMessage() {}

func (x *ScanVulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanVulnerability.ProtoReflect.Descriptor instead.
func (*ScanVulnerability) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *ScanVulnerability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanVulnerability) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ScanVulnerability) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *ScanVulnerability) GetFixedVersion() string {
	if x != nil {
		return x.FixedVersion
	}
	return ""
}

func (x *ScanVulnerability) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ScanVulnerability) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScanVulnerability) GetPrimaryUrl() string {
	if x != nil {
		return x.PrimaryUrl
	}
	return ""
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	StreamTypes   int32                  `protobuf:"varint,3,opt,name=streamTypes,proto3" json:"streamTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *StreamLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StreamLogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *StreamLogsRequest) GetStreamTypes() int32 {
	if x != nil {
		return x.StreamTypes
	}
	return 0
}

type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *LogEvent              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *StreamLogsResponse) GetEvent() *LogEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type LogsBetweenDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	StreamTypes   int32                  `protobuf:"varint,4,opt,name=streamTypes,proto3" json:"streamTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsBetweenDatesRequest) Reset() {
	*x = LogsBetweenDatesRequest{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsBetweenDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsBetweenDatesRequest) ProtoMessage() {}

func (x *LogsBetweenDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsBetweenDatesRequest.ProtoReflect.Descriptor instead.
func (*LogsBetweenDatesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *LogsBetweenDatesRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogsBetweenDatesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *LogsBetweenDatesRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *LogsBetweenDatesRequest) GetStreamTypes() int32 {
	if x != nil {
		return x.StreamTypes
	}
	return 0
}

type StreamRawBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	StreamTypes   int32                  `protobuf:"varint,4,opt,name=streamTypes,proto3" json:"streamTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRawBytesRequest) Reset() {
	*x = StreamRawBytesRequest{}
	mi := &file_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRawBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRawBytesRequest) ProtoMessage() {}

func (x *StreamRawBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRawBytesRequest.ProtoReflect.Descriptor instead.
func (*StreamRawBytesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *StreamRawBytesRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StreamRawBytesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *StreamRawBytesRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *StreamRawBytesRequest) GetStreamTypes() int32 {
	if x != nil {
		return x.StreamTypes
	}
	return 0
}

type StreamRawBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRawBytesResponse) Reset() {
	*x = StreamRawBytesResponse{}
	mi := &file_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRawBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRawBytesResponse) ProtoMessage() {}

func (x *StreamRawBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRawBytesResponse.ProtoReflect.Descriptor instead.
func (*StreamRawBytesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *StreamRawBytesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ContainerEvent        `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEventsResponse) GetEvent() *ContainerEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type StreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatsRequest) Reset() {
	*x = StreamStatsRequest{}
	mi := &file_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatsRequest) ProtoMessage() {}

func (x *StreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{18}
}

type StreamStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *ContainerStat         `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatsResponse) Reset() {
	*x = StreamStatsResponse{}
	mi := &file_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatsResponse) ProtoMessage() {}

func (x *StreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatsResponse.ProtoReflect.Descriptor instead.
func (*StreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *StreamStatsResponse) GetStat() *ContainerStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type HostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfoRequest) Reset() {
	*x = HostInfoRequest{}
	mi := &file_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoRequest) ProtoMessage() {}

func (x *HostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoRequest.ProtoReflect.Descriptor instead.
func (*HostInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{20}
}

type HostInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfoResponse) Reset() {
	*x = HostInfoResponse{}
	mi := &file_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoResponse) ProtoMessage() {}

func (x *HostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoResponse.ProtoReflect.Descriptor instead.
func (*HostInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *HostInfoResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

type StreamContainerStartedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerStartedRequest) Reset() {
	*x = StreamContainerStartedRequest{}
	mi := &file_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerStartedRequest) ProtoMessage() {}

func (x *StreamContainerStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerStartedRequest.ProtoReflect.Descriptor instead.
func (*StreamContainerStartedRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{22}
}

type StreamContainerStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerStartedResponse) Reset() {
	*x = StreamContainerStartedResponse{}
	mi := &file_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerStartedResponse) ProtoMessage() {}

func (x *StreamContainerStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerStartedResponse.ProtoReflect.Descriptor instead.
func (*StreamContainerStartedResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *StreamContainerStartedResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Action        ContainerAction        `protobuf:"varint,2,opt,name=action,proto3,enum=protobuf.ContainerAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerActionRequest) Reset() {
	*x = ContainerActionRequest{}
	mi := &file_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerActionRequest) ProtoMessage() {}

func (x *ContainerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerActionRequest.ProtoReflect.Descriptor instead.
func (*ContainerActionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *ContainerActionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerActionRequest) GetAction() ContainerAction {
	if x != nil {
		return x.Action
	}
	return ContainerAction_Start
}

type ContainerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerActionResponse) Reset() {
	*x = ContainerActionResponse{}
	mi := &file_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerActionResponse) ProtoMessage() {}

func (x *ContainerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerActionResponse.ProtoReflect.Descriptor instead.
func (*ContainerActionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{25}
}

type ContainerExecRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Command     []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ContainerExecRequest_Stdin
	//	*ContainerExecRequest_Resize
	Payload       isContainerExecRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecRequest) Reset() {
	*x = ContainerExecRequest{}
	mi := &file_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecRequest) ProtoMessage() {}

func (x *ContainerExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecRequest.ProtoReflect.Descriptor instead.
func (*ContainerExecRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *ContainerExecRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerExecRequest) GetPayload() isContainerExecRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ContainerExecRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ContainerExecRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ContainerExecRequest) GetResize() *ResizePayload {
	if x != nil {
		if x, ok := x.Payload.(*ContainerExecRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isContainerExecRequest_Payload interface {
	isContainerExecRequest_Payload()
}

type ContainerExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,3,opt,name=stdin,proto3,oneof"`
}

type ContainerExecRequest_Resize struct {
	Resize *ResizePayload `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

func (*ContainerExecRequest_Stdin) isContainerExecRequest_Payload() {}

func (*ContainerExecRequest_Resize) isContainerExecRequest_Payload() {}

type ResizePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizePayload) Reset() {
	*x = ResizePayload{}
	mi := &file_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizePayload) ProtoMessage() {}

func (x *ResizePayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizePayload.ProtoReflect.Descriptor instead.
func (*ResizePayload) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *ResizePayload) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizePayload) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ContainerExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecResponse) Reset() {
	*x = ContainerExecResponse{}
	mi := &file_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecResponse) ProtoMessage() {}

func (x *ContainerExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecResponse.ProtoReflect.Descriptor instead.
func (*ContainerExecResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *ContainerExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type ContainerAttachRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ContainerAttachRequest_Stdin
	//	*ContainerAttachRequest_Resize
	Payload       isContainerAttachRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerAttachRequest) Reset() {
	*x = ContainerAttachRequest{}
	mi := &file_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAttachRequest) ProtoMessage() {}

func (x *ContainerAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAttachRequest.ProtoReflect.Descriptor instead.
func (*ContainerAttachRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *ContainerAttachRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerAttachRequest) GetPayload() isContainerAttachRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ContainerAttachRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ContainerAttachRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ContainerAttachRequest) GetResize() *ResizePayload {
	if x != nil {
		if x, ok := x.Payload.(*ContainerAttachRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isContainerAttachRequest_Payload interface {
	isContainerAttachRequest_Payload()
}

type ContainerAttachRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ContainerAttachRequest_Resize struct {
	Resize *ResizePayload `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ContainerAttachRequest_Stdin) isContainerAttachRequest_Payload() {}

func (*ContainerAttachRequest_Resize) isContainerAttachRequest_Payload() {}

type ContainerAttachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerAttachResponse) Reset() {
	*x = ContainerAttachResponse{}
	mi := &file_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAttachResponse) ProtoMessage() {}

func (x *ContainerAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAttachResponse.ProtoReflect.Descriptor instead.
func (*ContainerAttachResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *ContainerAttachResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type UpdateNotificationConfigRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Subscriptions []*NotificationSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Dispatchers   []*NotificationDispatcher   `protobuf:"bytes,2,rep,name=dispatchers,proto3" json:"dispatchers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationConfigRequest) Reset() {
	*x = UpdateNotificationConfigRequest{}
	mi := &file_rpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationConfigRequest) ProtoMessage() {}

func (x *UpdateNotificationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationConfigRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateNotificationConfigRequest) GetSubscriptions() []*NotificationSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *UpdateNotificationConfigRequest) GetDispatchers() []*NotificationDispatcher {
	if x != nil {
		return x.Dispatchers
	}
	return nil
}

type UpdateNotificationConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationConfigResponse) Reset() {
	*x = UpdateNotificationConfigResponse{}
	mi := &file_rpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationConfigResponse) ProtoMessage() {}

func (x *UpdateNotificationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationConfigResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{32}
}

type GetNotificationStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatsRequest) Reset() {
	*x = GetNotificationStatsRequest{}
	mi := &file_rpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatsRequest) ProtoMessage() {}

func (x *GetNotificationStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{33}
}

type GetNotificationStatsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Stats         []*NotificationSubscriptionStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatsResponse) Reset() {
	*x = GetNotificationStatsResponse{}
	mi := &file_rpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatsResponse) ProtoMessage() {}

func (x *GetNotificationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationStatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{34}
}

func (x *GetNotificationStatsResponse) GetStats() []*NotificationSubscriptionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vtypes.proto\"\xb1\x01\n" +
	"\x15ListContainersRequest\x12C\n" +
	"\x06filter\x18\x01 \x03(\v2+.protobuf.ListContainersRequest.FilterEntryR\x06filter\x1aS\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.protobuf.RepeatedStringR\x05value:\x028\x01\"(\n" +
	"\x0eRepeatedString\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"M\n" +
	"\x16ListContainersResponse\x123\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x13.protobuf.ContainerR\n" +
	"containers\"\xd1\x01\n" +
	"\x14FindContainerRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x12B\n" +
	"\x06filter\x18\x02 \x03(\v2*.protobuf.FindContainerRequest.FilterEntryR\x06filter\x1aS\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.protobuf.RepeatedStringR\x05value:\x028\x01\"J\n" +
	"\x15FindContainerResponse\x121\n" +
	"\tcontainer\x18\x01 \x01(\v2\x13.protobuf.ContainerR\tcontainer\";\n" +
	"\x17RunContainerScanRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"H\n" +
	"\x18RunContainerScanResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.protobuf.ScanResultR\x06result\"\xc7\x01\n" +
	"\n" +
	"ScanResult\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12<\n" +
	"\vgeneratedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12/\n" +
	"\asummary\x18\x03 \x01(\v2\x15.protobuf.ScanSummaryR\asummary\x124\n" +
	"\aresults\x18\x04 \x03(\v2\x1a.protobuf.ScanTargetResultR\aresults\"\x97\x01\n" +
	"\vScanSummary\x12\x1a\n" +
	"\bcritical\x18\x01 \x01(\x05R\bcritical\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\x12\x16\n" +
	"\x06medium\x18\x03 \x01(\x05R\x06medium\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x05R\x03low\x12\x18\n" +
	"\aunknown\x18\x05 \x01(\x05R\aunknown\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x05R\x05total\"\x9b\x01\n" +
	"\x10ScanTargetResult\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12E\n" +
	"\x0fvulnerabilities\x18\x04 \x03(\v2\x1b.protobuf.ScanVulnerabilityR\x0fvulnerabilities\"\xe7\x01\n" +
	"\x11ScanVulnerability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vpackageName\x18\x02 \x01(\tR\vpackageName\x12*\n" +
	"\x10installedVersion\x18\x03 \x01(\tR\x10installedVersion\x12\"\n" +
	"\ffixedVersion\x18\x04 \x01(\tR\ffixedVersion\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"primaryUrl\x18\a \x01(\tR\n" +
	"primaryUrl\"\x89\x01\n" +
	"\x11StreamLogsRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12 \n" +
	"\vstreamTypes\x18\x03 \x01(\x05R\vstreamTypes\">\n" +
	"\x12StreamLogsResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.protobuf.LogEventR\x05event\"\xc1\x01\n" +
	"\x17LogsBetweenDatesRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12 \n" +
	"\vstreamTypes\x18\x04 \x01(\x05R\vstreamTypes\"\xbf\x01\n" +
	"\x15StreamRawBytesRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12 \n" +
	"\vstreamTypes\x18\x04 \x01(\x05R\vstreamTypes\",\n" +
	"\x16StreamRawBytesResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x15\n" +
	"\x13StreamEventsRequest\"F\n" +
	"\x14StreamEventsResponse\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.protobuf.ContainerEventR\x05event\"\x14\n" +
	"\x12StreamStatsRequest\"B\n" +
	"\x13StreamStatsResponse\x12+\n" +
	"\x04stat\x18\x01 \x01(\v2\x17.protobuf.ContainerStatR\x04stat\"\x11\n" +
	"\x0fHostInfoRequest\"6\n" +
	"\x10HostInfoResponse\x12\"\n" +
	"\x04host\x18\x01 \x01(\v2\x0e.protobuf.HostR\x04host\"\x1f\n" +
	"\x1dStreamContainerStartedRequest\"S\n" +
	"\x1eStreamContainerStartedResponse\x121\n" +
	"\tcontainer\x18\x01 \x01(\v2\x13.protobuf.ContainerR\tcontainer\"m\n" +
	"\x16ContainerActionRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x121\n" +
	"\x06action\x18\x02 \x01(\x0e2\x19.protobuf.ContainerActionR\x06action\"\x19\n" +
	"\x17ContainerActionResponse\"\xa8\x01\n" +
	"\x14ContainerExecRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x16\n" +
	"\x05stdin\x18\x03 \x01(\fH\x00R\x05stdin\x121\n" +
	"\x06resize\x18\x04 \x01(\v2\x17.protobuf.ResizePayloadH\x00R\x06resizeB\t\n" +
	"\apayload\"=\n" +
	"\rResizePayload\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"/\n" +
	"\x15ContainerExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\"\x90\x01\n" +
	"\x16ContainerAttachRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x121\n" +
	"\x06resize\x18\x03 \x01(\v2\x17.protobuf.ResizePayloadH\x00R\x06resizeB\t\n" +
	"\apayload\"1\n" +
	"\x17ContainerAttachResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\"\xaf\x01\n" +
	"\x1fUpdateNotificationConfigRequest\x12H\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\".protobuf.NotificationSubscriptionR\rsubscriptions\x12B\n" +
	"\vdispatchers\x18\x02 \x03(\v2 .protobuf.NotificationDispatcherR\vdispatchers\"\"\n" +
	" UpdateNotificationConfigResponse\"\x1d\n" +
	"\x1bGetNotificationStatsRequest\"]\n" +
	"\x1cGetNotificationStatsResponse\x12=\n" +
	"\x05stats\x18\x01 \x03(\v2'.protobuf.NotificationSubscriptionStatsR\x05stats2\xdc\n" +
	"\n" +
	"\fAgentService\x12U\n" +
	"\x0eListContainers\x12\x1f.protobuf.ListContainersRequest\x1a .protobuf.ListContainersResponse\"\x00\x12R\n" +
	"\rFindContainer\x12\x1e.protobuf.FindContainerRequest\x1a\x1f.protobuf.FindContainerResponse\"\x00\x12[\n" +
	"\x10RunContainerScan\x12!.protobuf.RunContainerScanRequest\x1a\".protobuf.RunContainerScanResponse\"\x00\x12K\n" +
	"\n" +
	"StreamLogs\x12\x1b.protobuf.StreamLogsRequest\x1a\x1c.protobuf.StreamLogsResponse\"\x000\x01\x12W\n" +
	"\x10LogsBetweenDates\x12!.protobuf.LogsBetweenDatesRequest\x1a\x1c.protobuf.StreamLogsResponse\"\x000\x01\x12W\n" +
	"\x0eStreamRawBytes\x12\x1f.protobuf.StreamRawBytesRequest\x1a .protobuf.StreamRawBytesResponse\"\x000\x01\x12Q\n" +
	"\fStreamEvents\x12\x1d.protobuf.StreamEventsRequest\x1a\x1e.protobuf.StreamEventsResponse\"\x000\x01\x12N\n" +
	"\vStreamStats\x12\x1c.protobuf.StreamStatsRequest\x1a\x1d.protobuf.StreamStatsResponse\"\x000\x01\x12o\n" +
	"\x16StreamContainerStarted\x12'.protobuf.StreamContainerStartedRequest\x1a(.protobuf.StreamContainerStartedResponse\"\x000\x01\x12C\n" +
	"\bHostInfo\x12\x19.protobuf.HostInfoRequest\x1a\x1a.protobuf.HostInfoResponse\"\x00\x12X\n" +
	"\x0fContainerAction\x12 .protobuf.ContainerActionRequest\x1a!.protobuf.ContainerActionResponse\"\x00\x12V\n" +
	"\rContainerExec\x12\x1e.protobuf.ContainerExecRequest\x1a\x1f.protobuf.ContainerExecResponse\"\x00(\x010\x01\x12\\\n" +
	"\x0fContainerAttach\x12 .protobuf.ContainerAttachRequest\x1a!.protobuf.ContainerAttachResponse\"\x00(\x010\x01\x12s\n" +
	"\x18UpdateNotificationConfig\x12).protobuf.UpdateNotificationConfigRequest\x1a*.protobuf.UpdateNotificationConfigResponse\"\x00\x12g\n" +
	"\x14GetNotificationStats\x12%.protobuf.GetNotificationStatsRequest\x1a&.protobuf.GetNotificationStatsResponse\"\x00B\x13Z\x11internal/agent/pbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_rpc_proto_goTypes = []any{
	(*ListContainersRequest)(nil),            // 0: protobuf.ListContainersRequest
	(*RepeatedString)(nil),                   // 1: protobuf.RepeatedString
	(*ListContainersResponse)(nil),           // 2: protobuf.ListContainersResponse
	(*FindContainerRequest)(nil),             // 3: protobuf.FindContainerRequest
	(*FindContainerResponse)(nil),            // 4: protobuf.FindContainerResponse
	(*RunContainerScanRequest)(nil),          // 5: protobuf.RunContainerScanRequest
	(*RunContainerScanResponse)(nil),         // 6: protobuf.RunContainerScanResponse
	(*ScanResult)(nil),                       // 7: protobuf.ScanResult
	(*ScanSummary)(nil),                      // 8: protobuf.ScanSummary
	(*ScanTargetResult)(nil),                 // 9: protobuf.ScanTargetResult
	(*ScanVulnerability)(nil),                // 10: protobuf.ScanVulnerability
	(*StreamLogsRequest)(nil),                // 11: protobuf.StreamLogsRequest
	(*StreamLogsResponse)(nil),               // 12: protobuf.StreamLogsResponse
	(*LogsBetweenDatesRequest)(nil),          // 13: protobuf.LogsBetweenDatesRequest
	(*StreamRawBytesRequest)(nil),            // 14: protobuf.StreamRawBytesRequest
	(*StreamRawBytesResponse)(nil),           // 15: protobuf.StreamRawBytesResponse
	(*StreamEventsRequest)(nil),              // 16: protobuf.StreamEventsRequest
	(*StreamEventsResponse)(nil),             // 17: protobuf.StreamEventsResponse
	(*StreamStatsRequest)(nil),               // 18: protobuf.StreamStatsRequest
	(*StreamStatsResponse)(nil),              // 19: protobuf.StreamStatsResponse
	(*HostInfoRequest)(nil),                  // 20: protobuf.HostInfoRequest
	(*HostInfoResponse)(nil),                 // 21: protobuf.HostInfoResponse
	(*StreamContainerStartedRequest)(nil),    // 22: protobuf.StreamContainerStartedRequest
	(*StreamContainerStartedResponse)(nil),   // 23: protobuf.StreamContainerStartedResponse
	(*ContainerActionRequest)(nil),           // 24: protobuf.ContainerActionRequest
	(*ContainerActionResponse)(nil),          // 25: protobuf.ContainerActionResponse
	(*ContainerExecRequest)(nil),             // 26: protobuf.ContainerExecRequest
	(*ResizePayload)(nil),                    // 27: protobuf.ResizePayload
	(*ContainerExecResponse)(nil),            // 28: protobuf.ContainerExecResponse
	(*ContainerAttachRequest)(nil),           // 29: protobuf.ContainerAttachRequest
	(*ContainerAttachResponse)(nil),          // 30: protobuf.ContainerAttachResponse
	(*UpdateNotificationConfigRequest)(nil),  // 31: protobuf.UpdateNotificationConfigRequest
	(*UpdateNotificationConfigResponse)(nil), // 32: protobuf.UpdateNotificationConfigResponse
	(*GetNotificationStatsRequest)(nil),      // 33: protobuf.GetNotificationStatsRequest
	(*GetNotificationStatsResponse)(nil),     // 34: protobuf.GetNotificationStatsResponse
	nil,                                      // 35: protobuf.ListContainersRequest.FilterEntry
	nil,                                      // 36: protobuf.FindContainerRequest.FilterEntry
	(*Container)(nil),                        // 37: protobuf.Container
	(*timestamppb.Timestamp)(nil),            // 38: google.protobuf.Timestamp
	(*LogEvent)(nil),                         // 39: protobuf.LogEvent
	(*ContainerEvent)(nil),                   // 40: protobuf.ContainerEvent
	(*ContainerStat)(nil),                    // 41: protobuf.ContainerStat
	(*Host)(nil),                             // 42: protobuf.Host
	(ContainerAction)(0),                     // 43: protobuf.ContainerAction
	(*NotificationSubscription)(nil),         // 44: protobuf.NotificationSubscription
	(*NotificationDispatcher)(nil),           // 45: protobuf.NotificationDispatcher
	(*NotificationSubscriptionStats)(nil),    // 46: protobuf.NotificationSubscriptionStats
}
var file_rpc_proto_depIdxs = []int32{
	35, // 0: protobuf.ListContainersRequest.filter:type_name -> protobuf.ListContainersRequest.FilterEntry
	37, // 1: protobuf.ListContainersResponse.containers:type_name -> protobuf.Container
	36, // 2: protobuf.FindContainerRequest.filter:type_name -> protobuf.FindContainerRequest.FilterEntry
	37, // 3: protobuf.FindContainerResponse.container:type_name -> protobuf.Container
	7,  // 4: protobuf.RunContainerScanResponse.result:type_name -> protobuf.ScanResult
	38, // 5: protobuf.ScanResult.generatedAt:type_name -> google.protobuf.Timestamp
	8,  // 6: protobuf.ScanResult.summary:type_name -> protobuf.ScanSummary
	9,  // 7: protobuf.ScanResult.results:type_name -> protobuf.ScanTargetResult
	10, // 8: protobuf.ScanTargetResult.vulnerabilities:type_name -> protobuf.ScanVulnerability
	38, // 9: protobuf.StreamLogsRequest.since:type_name -> google.protobuf.Timestamp
	39, // 10: protobuf.StreamLogsResponse.event:type_name -> protobuf.LogEvent
	38, // 11: protobuf.LogsBetweenDatesRequest.since:type_name -> google.protobuf.Timestamp
	38, // 12: protobuf.LogsBetweenDatesRequest.until:type_name -> google.protobuf.Timestamp
	38, // 13: protobuf.StreamRawBytesRequest.since:type_name -> google.protobuf.Timestamp
	38, // 14: protobuf.StreamRawBytesRequest.until:type_name -> google.protobuf.Timestamp
	40, // 15: protobuf.StreamEventsResponse.event:type_name -> protobuf.ContainerEvent
	41, // 16: protobuf.StreamStatsResponse.stat:type_name -> protobuf.ContainerStat
	42, // 17: protobuf.HostInfoResponse.host:type_name -> protobuf.Host
	37, // 18: protobuf.StreamContainerStartedResponse.container:type_name -> protobuf.Container
	43, // 19: protobuf.ContainerActionRequest.action:type_name -> protobuf.ContainerAction
	27, // 20: protobuf.ContainerExecRequest.resize:type_name -> protobuf.ResizePayload
	27, // 21: protobuf.ContainerAttachRequest.resize:type_name -> protobuf.ResizePayload
	44, // 22: protobuf.UpdateNotificationConfigRequest.subscriptions:type_name -> protobuf.NotificationSubscription
	45, // 23: protobuf.UpdateNotificationConfigRequest.dispatchers:type_name -> protobuf.NotificationDispatcher
	46, // 24: protobuf.GetNotificationStatsResponse.stats:type_name -> protobuf.NotificationSubscriptionStats
	1,  // 25: protobuf.ListContainersRequest.FilterEntry.value:type_name -> protobuf.RepeatedString
	1,  // 26: protobuf.FindContainerRequest.FilterEntry.value:type_name -> protobuf.RepeatedString
	0,  // 27: protobuf.AgentService.ListContainers:input_type -> protobuf.ListContainersRequest
	3,  // 28: protobuf.AgentService.FindContainer:input_type -> protobuf.FindContainerRequest
	5,  // 29: protobuf.AgentService.RunContainerScan:input_type -> protobuf.RunContainerScanRequest
	11, // 30: protobuf.AgentService.StreamLogs:input_type -> protobuf.StreamLogsRequest
	13, // 31: protobuf.AgentService.LogsBetweenDates:input_type -> protobuf.LogsBetweenDatesRequest
	14, // 32: protobuf.AgentService.StreamRawBytes:input_type -> protobuf.StreamRawBytesRequest
	16, // 33: protobuf.AgentService.StreamEvents:input_type -> protobuf.StreamEventsRequest
	18, // 34: protobuf.AgentService.StreamStats:input_type -> protobuf.StreamStatsRequest
	22, // 35: protobuf.AgentService.StreamContainerStarted:input_type -> protobuf.StreamContainerStartedRequest
	20, // 36: protobuf.AgentService.HostInfo:input_type -> protobuf.HostInfoRequest
	24, // 37: protobuf.AgentService.ContainerAction:input_type -> protobuf.ContainerActionRequest
	26, // 38: protobuf.AgentService.ContainerExec:input_type -> protobuf.ContainerExecRequest
	29, // 39: protobuf.AgentService.ContainerAttach:input_type -> protobuf.ContainerAttachRequest
	31, // 40: protobuf.AgentService.UpdateNotificationConfig:input_type -> protobuf.UpdateNotificationConfigRequest
	33, // 41: protobuf.AgentService.GetNotificationStats:input_type -> protobuf.GetNotificationStatsRequest
	2,  // 42: protobuf.AgentService.ListContainers:output_type -> protobuf.ListContainersResponse
	4,  // 43: protobuf.AgentService.FindContainer:output_type -> protobuf.FindContainerResponse
	6,  // 44: protobuf.AgentService.RunContainerScan:output_type -> protobuf.RunContainerScanResponse
	12, // 45: protobuf.AgentService.StreamLogs:output_type -> protobuf.StreamLogsResponse
	12, // 46: protobuf.AgentService.LogsBetweenDates:output_type -> protobuf.StreamLogsResponse
	15, // 47: protobuf.AgentService.StreamRawBytes:output_type -> protobuf.StreamRawBytesResponse
	17, // 48: protobuf.AgentService.StreamEvents:output_type -> protobuf.StreamEventsResponse
	19, // 49: protobuf.AgentService.StreamStats:output_type -> protobuf.StreamStatsResponse
	23, // 50: protobuf.AgentService.StreamContainerStarted:output_type -> protobuf.StreamContainerStartedResponse
	21, // 51: protobuf.AgentService.HostInfo:output_type -> protobuf.HostInfoResponse
	25, // 52: protobuf.AgentService.ContainerAction:output_type -> protobuf.ContainerActionResponse
	28, // 53: protobuf.AgentService.ContainerExec:output_type -> protobuf.ContainerExecResponse
	30, // 54: protobuf.AgentService.ContainerAttach:output_type -> protobuf.ContainerAttachResponse
	32, // 55: protobuf.AgentService.UpdateNotificationConfig:output_type -> protobuf.UpdateNotificationConfigResponse
	34, // 56: protobuf.AgentService.GetNotificationStats:output_type -> protobuf.GetNotificationStatsResponse
	42, // [42:57] is the sub-list for method output_type
	27, // [27:42] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_types_proto_init()
	file_rpc_proto_msgTypes[26].OneofWrappers = []any{
		(*ContainerExecRequest_Stdin)(nil),
		(*ContainerExecRequest_Resize)(nil),
	}
	file_rpc_proto_msgTypes[29].OneofWrappers = []any{
		(*ContainerAttachRequest_Stdin)(nil),
		(*ContainerAttachRequest_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
